apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-legacy
  labels:
    {{- include "pubquiz-frontend.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Release.Name }}-legacy-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.legacyHost | quote }}
      secretName: {{ .Release.Name }}-legacy-tls
  rules:
    - host: {{ .Values.ingress.legacyHost | quote }}
      http:
        paths:
          - path: /quizzes
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  name: http
